### PR TITLE
Added entity_manager tests (💯% 🔥🔥🔥) 

### PR DESCRIPTION
**Pull request by Peter-JanGootzen**
# Description

This PR adds tests for the entity_manager.hpp

# How can this be tested?

Run the tests :)
For code coverage:
- use clang++ with `CXX=clang++`
- run the BrickEngine_Test binary
- `llvm-profdata merge -sparse default.profraw -o default.profdata`
- `llvm-cov report ./BrickEngine_Test ../lib ../include --instr-profile=default.profdata`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Included 1 or more screenshots
- [x] Code is const correct

### CODE REVIEW

**Comment by Peter-JanGootzen** [comment]
I accidentally started this branch from the not yet merged `physics-tweaking` branch, fixed it with a cherry-pick and force-push. All is :100: now.

**Comment by Bram-Boris** [comment]
Yep, as @LuukSantegoeds said. I cannot find the default.profaw file.

**Comment by Peter-JanGootzen** [comment]
> image
> 
> Ik krijg deze error wanneer ik make doe, idk of ik zelf wat fout doe of wat :p.

I have no clue why that happens on your machine. try `rm -rf *` in the build folder and then build again.

@LuukSantegoeds and @Bram-Boris I fixed the default.profraw not being generated.

**Comment by Peter-JanGootzen** [comment]
I am not able to reproduce the bug of @JanSchollaert once again, I feel it has something to do with building multiple executables at the same time because it says that there are multiple mains being linked. But when I turn all targets on, I don't get this error.

**Pull request merged**
